# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: h2c.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\th2c.proto\x12\x03H2C\"\x18\n\x04\x43\x61ll\x12\x10\n\x08payloads\x18\x01 \x01(\t\",\n\x08Response\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08payloads\x18\x03 \x01(\t24\n\x07\x43onnect\x12)\n\x0b\x63ommunicate\x12\t.H2C.Call\x1a\r.H2C.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'h2c_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CALL']._serialized_start=18
  _globals['_CALL']._serialized_end=42
  _globals['_RESPONSE']._serialized_start=44
  _globals['_RESPONSE']._serialized_end=88
  _globals['_CONNECT']._serialized_start=90
  _globals['_CONNECT']._serialized_end=142
# @@protoc_insertion_point(module_scope)
