apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: airflow
  name: airflow-worker-compute-avg-distributed-extract
  annotations:
    dag_id: compute_avg_distributed
    task_id: extract
spec:
  template:
    spec:
      containers:
        - image: "nehalem90/airflow-worker:latest"
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 8081
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW_IS_K8S_EXECUTOR_POD
              value: "True"
            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-metadata
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-airflow-metadata
                  key: connection
