apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: airflow-grpc-test-v2
  namespace: airflow-grpc
spec:
  template:
    spec:
      containers:
      - image: whonamihwp/h2c-kn
        ports:
        - name: h2c
          containerPort: 8080

