# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import h2c_pb2 as h2c__pb2


class H2CStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.communicate = channel.unary_unary(
                '/H2C.H2C/communicate',
                request_serializer=h2c__pb2.CommunicateMsg.SerializeToString,
                response_deserializer=h2c__pb2.CommunicateMsg.FromString,
                )


class H2CServicer(object):
    """Missing associated documentation comment in .proto file."""

    def communicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_H2CServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'communicate': grpc.unary_unary_rpc_method_handler(
                    servicer.communicate,
                    request_deserializer=h2c__pb2.CommunicateMsg.FromString,
                    response_serializer=h2c__pb2.CommunicateMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'H2C.H2C', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class H2C(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def communicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/H2C.H2C/communicate',
            h2c__pb2.CommunicateMsg.SerializeToString,
            h2c__pb2.CommunicateMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
